UrunSiparis/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UrunSiparis.Models
{
    public enum City
    {

        Adana,
        Adıyaman,
        Afyon,
        Ağrı,
        Amasya,
        Ankara,
        Antalya,
        Artvin,
        Aydın,
        Balıkesir,
        Bilecik,
        Bingöl,
        Bitlis,
        Bolu,
        Burdur,
        Bursa,
        Çanakkale,
        Çankırı,
        Çorum,
        Denizli,
        Diyarbakır,
        Edirne,
        Elazığ,
        Erzincan,
        Erzurum,
        Eskişehir,
        Gaziantep,
        Giresun,
        Gümüşhane,
        Hakkari,
        Hatay,
        Isparta,
        Mersin,
        İstanbul,
        İzmir,
        Kars,
        Kastamonu,
        Kayseri,
        Kırklareli,
        Kırşehir,
        Kocaeli,
        Konya,
        Kütahya,
        Malatya,
        Manisa,
        Kahramanmaraş,
        Mardin,
        Muğla,
        Muş,
        Nevşehir,
        Niğde,
        Ordu,
        Rize,
        Sakarya,
        Samsun,
        Siirt,
        Sinop,
        Sivas,
        Tekirdağ,
        Tokat,
        Trabzon,
        Tunceli,
        Şanlıurfa,
        Uşak,
        Van,
        Yozgat,
        Zonguldak,
        Aksaray,
        Bayburt,
        Karaman,
        Kırıkkale,
        Batman,
        Şırnak,
        Bartın,
        Ardahan,
        Iğdır,
        Yalova,
        Karabük,
        Kilis,
        Osmaniye,
        Düzce,


    }
}

UrunSiparis/Models/ErrorViewModel.cs
using System;

namespace UrunSiparis.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UrunSiparis/Models/UrunSiparisModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UrunSiparis.Models
{
    public class UrunSiparisModel
    {

        public int Id { get; set; }
        [Required]
        [Display(Name = "Ad")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Soyad")]
        public string LastName { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Adres")]
        public string Adress { get; set; }
        [Required]
        [Display(Name = "Şehir")]
        public City City { get; set; }
        [Required]
        [Display(Name = "Ülke")]
        public string Country { get; set; }

    }
}

UrunSiparis/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UrunSiparis.Models;

namespace UrunSiparis.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Hakkımda()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UrunSiparis/Controllers/UrunSiparisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UrunSiparis.Data;
using UrunSiparis.Models;

namespace UrunSiparis.Controllers
{
    public class UrunSiparisController : Controller
    {
        private readonly UrunSiparisContext _context;

        public UrunSiparisController(UrunSiparisContext context)
        {
            _context = context;
        }

        // GET: UrunSiparis
        public async Task<IActionResult> Index()
        {
            return View(await _context.UrunSiparisModel.ToListAsync());
        }

        // GET: UrunSiparis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urunSiparisModel = await _context.UrunSiparisModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (urunSiparisModel == null)
            {
                return NotFound();
            }

            return View(urunSiparisModel);
        }

        // GET: UrunSiparis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UrunSiparis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,Adress,City,Country")] UrunSiparisModel urunSiparisModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(urunSiparisModel);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Öğe başarıyla eklendi!";
                return RedirectToAction(nameof(Index));
            }
            return View(urunSiparisModel);
        }

        // GET: UrunSiparis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urunSiparisModel = await _context.UrunSiparisModel.FindAsync(id);
            if (urunSiparisModel == null)
            {
                return NotFound();
            }
            return View(urunSiparisModel);
        }

        // POST: UrunSiparis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,Adress,City,Country")] UrunSiparisModel urunSiparisModel)
        {
            if (id != urunSiparisModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(urunSiparisModel);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Öğe başarıyla güncellendi!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UrunSiparisModelExists(urunSiparisModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(urunSiparisModel);
        }

        // GET: UrunSiparis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urunSiparisModel = await _context.UrunSiparisModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (urunSiparisModel == null)
            {
                return NotFound();
            }

            return View(urunSiparisModel);
        }

        // POST: UrunSiparis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var urunSiparisModel = await _context.UrunSiparisModel.FindAsync(id);
            _context.UrunSiparisModel.Remove(urunSiparisModel);
            await _context.SaveChangesAsync();
            TempData["Success"] = "Öğe başarıyla silindi!";
            return RedirectToAction(nameof(Index));
        }

        private bool UrunSiparisModelExists(int id)
        {
            return _context.UrunSiparisModel.Any(e => e.Id == id);
        }
    }
}

UrunSiparis/Views/Home/Hakkımda.cshtml
@{
    ViewData["Title"] = "Hakkımda";
}

<div class="text-center">
    <h1 class="display-4">Hoşgeldiniz</h1>
    <img src="/İmage/ben.jpg" alt="Resmim" />
    <p>Sivas Cumhuriyet Üniversitesi Bilgisayar Mühendisliği Bölümü 4.sınıf öğrencisiyim.</p>
    <p>Detaysoft şirketinde Junior dotnet developer olarak çalışıyorum.</p>
    <p>GitHub Adresim<a href="https://github.com/bugrakbas">Buradan ulaşabilrsiniz.</a></p>
    <p>Sorularınız için<a href="mailto:bugrahanakbs@gmail.com">buradan mail atabilirsiniz</a></p>
</div>

UrunSiparis/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hoşgeldiniz</h1>
    <p>Bu proje örnek bir mvc projesidir</p>
</div>

UrunSiparis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UrunSiparis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UrunSiparis" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class=" nac-item">
                            <a class=" nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Hakkımda">Hakkımda</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["Success"] != null)
            {
                <div class="alert alert-success">
                    @TempData["Success"]
                </div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="alert alert-danger">
                    @TempData["Error"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - UrunSiparis - <a asp-area="" asp-controller="Home" asp-action="Hakkımda">Hakkımda</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

UrunSiparis/Views/UrunSiparis/Create.cshtml
@model UrunSiparis.Models.UrunSiparisModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UrunSiparisModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                @*<select asp-for="City" class="form-control"></select>*@
                <select asp-for="City" asp-items="Html.GetEnumSelectList<City>()" class="from-control">
                    <option value=" "></option>
                </select>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UrunSiparis/Views/UrunSiparis/Delete.cshtml
@model UrunSiparis.Models.UrunSiparisModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UrunSiparisModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

UrunSiparis/Views/UrunSiparis/Details.cshtml
@model UrunSiparis.Models.UrunSiparisModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UrunSiparisModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

UrunSiparis/Views/UrunSiparis/Edit.cshtml
@model UrunSiparis.Models.UrunSiparisModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UrunSiparisModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                @*<select asp-for="City" class="form-control"></select>*@
                <select asp-for="City" asp-items="Html.GetEnumSelectList<City>()" class="from-control">
                    <option value=" "></option>
                </select>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UrunSiparis/Views/UrunSiparis/Index.cshtml
@model IEnumerable<UrunSiparis.Models.UrunSiparisModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>

        }
    </tbody>
</table>